---
title: Fetching Financial Data Sets
author: Marius Hofert
date: '`r Sys.Date()`'
output:
  html_vignette:
    css: style.css
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Fetching Financial Data Sets}
---
```{r, message=FALSE}
require(qrmtools)
require(xts)

end <- "2015-12-31" # last trading day we consider
```

## 1 Stock data

```{r, eval=FALSE}
## Radioshack
## Defaulted early 2015 => Yahoo Finance only has
## https://www.google.com/finance/historical?q=OTCMKTS%3ARSHCQ&ei=N_CAVvnUKsjjsAHJ3YvwDg
## but no adjusted close price (and values differ slightly)
## => Use the data from Yahoo Finance as of 2015-01-21 here (collected by Alex J. McNeil)
RSHCQ <- read.table("data_RSHCQ.csv", sep=",", header=TRUE, row.names=1) # get data
dates <- as.Date(row.names(RSHCQ), format="%Y-%m-%d") # get dates
RSHCQ <- xts(RSHCQ, dates)[,"Adj.Close"] # create an xts object
colnames(RSHCQ) <- "RSHCQ"
save(RSHCQ, file="RSHCQ.rda", compress="xz")
```


## 2 Stock index data

```{r, eval=FALSE}
## S&P 500
SP500 <- get_data("^GSPC", to=end)
save(SP500, file="SP500.rda", compress="xz")

## Dow Jones
DJ <- get_data("^DJI", to=end)
save(DJ, file="DJ.rda", compress="xz")

## NASDAQ 100
NASDAQ <- get_data("^NDX", to=end)
save(NASDAQ, file="NASDAQ.rda", compress="xz")

## FTSE 100
FTSE <- get_data("^FTSE", to=end)
save(FTSE, file="FTSE.rda", compress="xz")

## SMI (Swiss Market Index)
SMI <- get_data("^SSMI", to=end)
save(SMI, file="SMI.rda", compress="xz")

## Euro Stoxx 50 (stock index of Eurozone stocks)
EURSTOXX <- get_data("^STOXX50E", to=end)
save(EURSTOXX, file="EURSTOXX.rda", compress="xz")

## CAC (Cotation Assistee en Continu)
CAC <- get_data("^FCHI", to=end)
save(CAC, file="CAC.rda", compress="xz")

## DAX (Deutscher Aktienindex)
DAX <- get_data("^GDAXI", to=end)
save(DAX, file="DAX.rda", compress="xz")

## CSI (China Securities Index)
CSI <- get_data("000300.SS", to=end)
save(CSI, file="CSI.rda", compress="xz")

## HSI (Hang Seng Index; open to overseas investors)
HSI <- get_data("^HSI", to=end)
save(HSI, file="HSI.rda", compress="xz")

## SSEC (Shanghai Stock Exchange Composite Index; restricted to domestic investors)
SSEC <- get_data("000001.SS", to=end)
save(SSEC, file="SSEC.rda", compress="xz")

## NIKKEI
NIKKEI <- get_data("^N225", to=end)
save(NIKKEI, file="NIKKEI.rda", compress="xz")
```


## 3 FX data

```{r, eval=FALSE}
## Check that 1/"1 unit cur A in cur B" ~= "cur B in cur A"
if(FALSE) {
    GBP_USD <- get_data("GBP/USD", to=end, src="oanda") # 1 GBP in USD
    USD_GBP <- get_data("USD/GBP", to=end, src="oanda") # 1 USD in GBP
    ## Check that 1/GBP_USD ~= USD_GBP
    plot(USD_GBP)
    lines(1/GBP_USD, col="blue")
    summary(USD_GBP-1/GBP_USD) # as good as equal
}

## Choose a reasonable 'from' date
## FX involving EUR are only available >= 1998-12-14
from <- "2000-01-01"
```


### 3.1 */USD

```{r, eval=FALSE}
## CAD/USD
CAD_USD <- get_data("CAD/USD", from=from, to=end, src="oanda")
head(CAD_USD)
save(CAD_USD, file="CAD_USD.rda", compress="xz")

## GBP/USD
GBP_USD <- get_data("GBP/USD", from=from, to=end, src="oanda")
head(GBP_USD)
save(GBP_USD, file="GBP_USD.rda", compress="xz")

## EUR/USD
EUR_USD <- get_data("EUR/USD", from=from, to=end, src="oanda")
head(EUR_USD)
save(EUR_USD, file="EUR_USD.rda", compress="xz")

## CHF/USD
CHF_USD <- get_data("CHF/USD", from=from, to=end, src="oanda")
head(CHF_USD)
save(CHF_USD, file="CHF_USD.rda", compress="xz")

## JPY/USD
## Note: We use JPY/USD = 1/(USD/JPY) here since JPY/USD only
##       has four digits which is to little here
JPY_USD <- 1/get_data("USD/JPY", from=from, to=end, src="oanda")
head(JPY_USD)
save(JPY_USD, file="JPY_USD.rda", compress="xz")

## CNY/USD
CNY_USD <- get_data("CNY/USD", from=from, to=end, src="oanda")
head(CNY_USD)
save(CNY_USD, file="CNY_USD.rda", compress="xz")
```


### 3.2 */GBP

```{r, eval=FALSE}
## CAD/GBP
CAD_GBP <- get_data("CAD/GBP", from=from, to=end, src="oanda")
head(CAD_GBP)
save(CAD_GBP, file="CAD_GBP.rda", compress="xz")

## GBP/GBP
USD_GBP <- get_data("USD/GBP", from=from, to=end, src="oanda")
head(USD_GBP)
save(USD_GBP, file="USD_GBP.rda", compress="xz")

## EUR/GBP
EUR_GBP <- get_data("EUR/GBP", from=from, to=end, src="oanda")
head(EUR_GBP)
save(EUR_GBP, file="EUR_GBP.rda", compress="xz")

## CHF/GBP
CHF_GBP <- get_data("CHF/GBP", from=from, to=end, src="oanda")
head(CHF_GBP)
save(CHF_GBP, file="CHF_GBP.rda", compress="xz")

## JPY/GBP
## Note: We use JPY/GBP = 1/(GBP/JPY) here since JPY/GBP only
##       has four digits which is to little here
JPY_GBP <- 1/get_data("GBP/JPY", from=from, to=end, src="oanda")
head(JPY_GBP)
save(JPY_GBP, file="JPY_GBP.rda", compress="xz")

## CNY/GBP
CNY_GBP <- get_data("CNY/GBP", from=from, to=end, src="oanda")
head(CNY_GBP)
save(CNY_GBP, file="CNY_GBP.rda", compress="xz")
```


## 4 Volatility data

```{r, eval=FALSE}
## VIX
VIX <- get_data("^VIX", to=end)
save(VIX, file="VIX.rda", compress="xz")
```


## 5 Commodity data

```{r, eval=FALSE}
## Oil
## Note: - Brent Crude is the benchmark (https://en.wikipedia.org/wiki/Brent_Crude)
##       - See https://www.quandl.com/data/FRED?keyword=dcoil for the tickers
##         => https://www.quandl.com/data/FRED/DCOILBRENTEU-Crude-Oil-Prices-Brent-Europe
##       - FRED = Federal Reserve Economic Data => FRED data can also be directly
##         obtained via getSymbols (and thus get_data).
##       - get_data("DCOILBRENTEU", to=end, src="FRED") would have also worked
OIL_Brent <- get_data("FRED/DCOILBRENTEU", to=end, src="quandl") # Brent Crude price in USD per barrel (USD/bbl)
colnames(OIL_Brent) <- "OIL_Brent"
stopifnot(!is.na(OIL_Brent))
save(OIL_Brent, file="OIL_Brent.rda", compress="xz")

## Gold
## See https://www.quandl.com/data/WGC/GOLD_DAILY_USD-Gold-Prices-Daily-Currency-USD (WGC = World Gold Council)
GOLD <- get_data("WGC/GOLD_DAILY_USD", to=end, src="quandl")
colnames(GOLD) <- "GOLD"
stopifnot(!is.na(GOLD))
save(GOLD, file="GOLD.rda", compress="xz")
```
