---
title: Fetching Financial Data Sets
author: Marius Hofert
date: '`r Sys.Date()`'
output:
  html_vignette:
    css: style.css
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Fetching Financial Data Sets}
---
```{r, message=FALSE}
require(qrmtools)
require(xts)

start <- "1980-01-01" # first day we consider
end   <- "2015-12-31" # last day we consider
```

## S&P 500 constituents data

% Algorithm for S&P 500 (constituents not available on finance.yahoo.com):
% 1) Copy the ticker table from https://www.cboe.com/products/snp500.aspx without header
% 2) Paste it to a new document in LibreOffice
% 3) Remove all columns except: Ticker, GICS, GICS subsectors
% 4) Save it as a .csv file (when asked, make sure ',' is chosen as delimiter)

```{r, eval=FALSE}
## S&P 500 constituents
## See https://www.cboe.com/products/snp500.aspx (updated 2015-10-12)
SP500_const_info <- read.table("data_SP500_const_tab.csv", sep=",")
colnames(SP500_const_info) <- c("Ticker", "Sector", "Subsector")
SP500_const <- get_data(SP500_const_info[,1], to=end) # get data for these tickers (takes a while)
save(SP500_const, SP500_const_info, file="SP500_const.rda", compress="xz")

if(FALSE) {
    image(x=index(SP500_const), y=seq_len(ncol(SP500_const)), z=is.na(SP500_const),
          col=c("white", "black"), xlab="Time t", ylab="Stock j",
          main="Plot of NAs among the S&P 500 constituents")
    mtext("Black: NA; White: Data available", side=4, line=1, adj=0)
}
```
